spring.application.name=CineBook
spring.datasource.url=jdbc:mysql://localhost:3306/cinebook
spring.datasource.username=root
spring.datasource.password=Payal24May
server.port=8082
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true